// eslint-disable-next-line import/no-anonymous-default-export
export default {

  Products: [
    {
      id: 1,
      title:'Nike Shoes',
      image: '../images/product1.jpg',
      price: 100,
      discount: 10,
      discountprice: 90,
      category: 'Shoes',
      subcategory: 'Top Deals',
      brand: 'Nike',
      colors: 'Red',
      description: 'These fashion sneakers from Nike has a clean look and stylish modern design for increased comfort. This is your go-to style for casual wear. It is lightweight and has some nice detailing to increase comfort. Pair these fashion sneakers with jeans and casual t-shirt.',
    },
    {
      id: 2,
      title:'XBOX One Controller',
      image: '../images/product5.jpg',
      price: 30,
      discount: 20,
      discountprice: 25,
      category: 'Gaming',
      subcategory: 'Top Deals',
      brand: 'Microsoft',
      colors: 'White',
      description: 'The Microsoft Xbox One Wireless Controller gives you a great experience and lets you control the game smoothly and in precision. This controller justifies the brand name and comes with many features that allow you to have a great experience while indulging in any play. You can easily control the various triggers and functions as it renders smoothing functioning without any delay or hindrances.',
    },
    {
      id: 3,
      title:'One Step 2',
      image: '../images/product3.jpg',
      price: 100,
      discount: 50,
      discountprice: 50,
      category: 'Cameras',
      subcategory: 'Top Deals',
      brand: '',
      colors: '',
      description: '',
    },
    {
      id: 4,
      title:'Red Diamond',
      image: '../images/product7.jpg',
      price: 70,
      discount: 42,
      discountprice: 30,
      category: 'Fragrance',
      subcategory: 'Top Deals',
      brand: '',
      colors: '',
      description: 'Diamonds and Rubies by Elizabeth Taylor for Women, Eau De Toilette Spray, 3.3-Ounce',
    },
    {
      id: 5,
      title:'Nikon D750',
      image: '../images/product4.jpg',
      price: 300,
      discount: '',
      discountprice: '',
      category: 'Cameras',
      subcategory: 'Recommended for you',
      brand: 'Nikon',
      colors: 'Black',
      description: 'The Nikon D750 FX-Format Digital SLR Body Only Camera brings dazzling image quality, cinematic video capabilities and pro-inspired handling in a nimble design with a tilting Vari-angle LCD and built-in Wi-Fi connectivity. Enthusiasts upgrading from a DX-format D-SLR will marvel at the D750 full-frame performance.',
    },
    {
      id: 6,
      title:'Rayban RB2132',
      image: '../images/product2.jpg',
      price: 500,
      discount: '',
      discountprice: '',
      category: 'Glasses',
      subcategory: 'Recommended for you',
      brand: 'Rayban',
      colors: 'Black',
      description: 'Ray-Ban RB2132 New Wayfarer sunglasses take the iconic shape of the Classic Wayfarer and infuse a slightly smaller frame and softer eye shape perfect for women and men. These unisex sunglasses are polarized, reduce eye strain, and improve visibility during glaring light conditions. All Ray-Ban sunglasses are made from superior materials, and these unisex polarized sunglasses are no exception. RB2132 unisex Wayfarer frames are manufactured from durable nylon, making them lightweight and able to hold up against frequent use. Our polarized Wayfarer sunglasses utilize famous G-15 polarized lenses, which are prescription ready and made from glass.',
    },
    {
      id: 7,
      title:'Vinta',
      image: '../images/product6.jpg',
      price: 15,
      discount: '',
      discountprice: '',
      category: 'Bags',
      subcategory: 'Recommended for you',
      brand: 'Vinta',
      colors: '',
      description: 'This bag is perfect for a lifestyle of adventure, trekking to and from the studio, the office or the mountains.',
    },
    {
      id: 8,
      title:'Fossil FS4656IE',
      image: '../images/product8.jpg',
      price: 160,
      discount: '',
      discountprice: '',
      category: 'Watches',
      subcategory: 'Recommended for you',
      brand: 'Fossil',
      colors: '',
      description: 'From classic chronographs to the newest smartwatches, we’ve got the watch styles you love. The best part is that our wide selection of timepieces comes in enough styles, colors and designs to keep your style fresh and fun for years to come. Whether you’re looking for an everyday watch, something for a special occasion or a gift for loved ones, you’ll find it here. We’ve got leather strap watches, stainless steel, mesh and silicone for whatever material suits you best. Part effortless cool, part extreme functionality—our Machine watch is the ultimate masculine essential With a rugged design, oversized case and aeronautical-inspired gauges, this industrial style is right on time Make a statement with this dramatic timepiece.',
    },
  ],
  
  users:[
    {
      userName: "user1",
      email:'test1@gmail.com',
      password: "pass1"
    },
    {
      userName: "user2",
      email:'test2@gmail.com',
      password: "pass2"
    }
  ]
}